### ISSUE TITLE
mirror value doesn't depend on ImageCapture

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/snapshot#8]
I think you can toggle `mirror` class to the video element even if `ImageCapture` is not available in https://github.com/GoogleChrome/snapshot/blob/550a559ed828a44cf697b5a33fdbbb592fbb4cd7/src/capture-view.ts#L55-L58

```ts
        const constraints = track.getConstraints();
        const mirror = (constraints.facingMode === 'user');
        this.videoElement.classList.toggle('mirror', mirror);

        if ('ImageCapture' in window) {
          const track = stream.getVideoTracks()[0];
          this.capture = new ImageCapture(track);
        }

**Comment by wibblymat** [comment]
It turns out that this whole chunk of code is one big bug, so is getting rewritten. In particular, I'm getting the facing mode from the constraints, but that doesn't tell me about the actual camera. I need to get it from the camera settings instead which isn't even implemented in Chrome.

For now, mirror is going to be a UI toggle that defaults to not-mirrored, and we'll add autodetect back in later.
